name: Deploy TO S3 Invalidate Cloudfront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 코드 불러오기
        run: actions/checkout@v4

      - name: 파일 출력하기
        run: ls
