name: Deploy TO S3 Invalidate Cloudfront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 코드 불러오기
        uses: actions/checkout@v5

      - name: 의존성 설치
        run: npm i

      - name: 빌드하기
        run: npm run bulid

      - name: 디버깅
        run: |
          ls
          cd dist
          ls
